- job:
    name: monasca-tempest-base
    parent: legacy-dsvm-base
    run: playbooks/legacy/monasca-tempest-base/run.yaml
    post-run: playbooks/legacy/monasca-tempest-base/post.yaml
    timeout: 7800
    required-projects:
      - openstack/devstack-gate
      - openstack/monasca-agent
      - openstack/monasca-api
      - openstack/monasca-common
      - openstack/monasca-grafana-datasource
      - openstack/monasca-notification
      - openstack/monasca-persister
      - openstack/monasca-statsd
      - openstack/monasca-thresh
      - openstack/monasca-ui
      - openstack/python-monascaclient
      - openstack/tempest
      - openstack/monasca-tempest-plugin
    vars:
      database: mysql
    irrelevant-files:
      - ^.*\.rst$
      - ^.*\.md$
      - ^doc/.*$
      - ^releasenotes/.*$

- job:
    name: monasca-tempest-python-influxdb
    parent: monasca-tempest-base
    vars:
      tsdb: influxdb
      api_lang: python
      persister_lang: python

- job:
    name: monasca-tempest-java-influxdb
    parent: monasca-tempest-base
    vars:
      tsdb: influxdb
      api_lang: java
      persister_lang: java

- job:
    name: monasca-tempest-python-cassandra
    parent: monasca-tempest-base
    vars:
      tsdb: cassandra
      api_lang: python
      persister_lang: python
      tempest_test_regex: (?!.*\[.*\btimerange\b.*\])(^monasca_tempest_tests.tests.api)

- job:
    name: monasca-tempest-java-cassandra
    parent: monasca-tempest-base
    vars:
      tsdb: cassandra
      api_lang: python
      persister_lang: java
      tempest_test_regex: (?!.*\[.*\btimerange\b.*\])(^monasca_tempest_tests.tests.api)

- project:
    templates:
      - openstack-python-jobs
      - openstack-python35-jobs
      - check-requirements
      - release-notes-jobs
    check:
      jobs:
        - monasca-tempest-python-influxdb
        - monasca-tempest-java-influxdb
        - monasca-tempest-python-cassandra
        - monasca-tempest-java-cassandra
        - openstack-tox-lower-constraints
        - legacy-monasca-api-maven-build
        - openstack-tox-cover
        - build-openstack-sphinx-docs
    gate:
      queue: monasca
      jobs:
        - monasca-tempest-python-influxdb
        - monasca-tempest-java-influxdb
        - monasca-tempest-python-cassandra
        - monasca-tempest-java-cassandra
        - openstack-tox-lower-constraints
        - legacy-monasca-api-maven-build
        - openstack-tox-cover
        - build-openstack-sphinx-docs
    post:
      jobs:
        - legacy-monasca-api-localrepo-upload
        - publish-openstack-sphinx-docs
